### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [JarfigNewton/firstyfirst#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by JarfigNewton** [comment]
Thanks for the suggestion! I did a little research and discovered the "viewport" meta tag. It works great on my device!

**Comment by Mikeysax** [comment]
:+1:
